### ISSUE TITLE
Tipps for better speed?

### ISSUE THREAD

**Issue by Serpens66** [elarivie/pyReaderWriterLock#10]
Hi again :)

According to my speed tests, the usage of RWLockFair read lock is ~14 times slower than using a threading.Lock() (aquire and release).
I guess this is because the code is in python, while threading lock code may be in C.

But do you have tipps how to get faster read/write locks? Eg. real time updates for finance orderbooks while also having alot of reads would be one usecase, where I think it is faster to use regular locks for every operation instead of your read/write lock.

Maybe there is a patch or the usage of Cython is possible?

**Comment by elarivie** [comment]
Hi @Serpens66 

Your benchmark showing a 14x difference in lock/release cycle is not unexpected.


A ReaderWriterLock will always lose a race against a Lock in a benchmark measuring the speed of lock/release cycle.  This is true independently of the programming language being use...

Internally readerwriter locks use locks, so having a readerwriter lock to outperform a lock on the sole criteria of lock/release cycle is impossible.


Your benchmark can statically be explained by simply looking at the constructor of the different reader writer lock you will notice that
 - The Fair algorithm internally use three locks https://github.com/elarivie/pyReaderWriterLock/blob/5569662f3cab997a22b50522794afe0258c09850/readerwriterlock/rwlock.py#L318
 - The Reader algorithm internally use two locks https://github.com/elarivie/pyReaderWriterLock/blob/5569662f3cab997a22b50522794afe0258c09850/readerwriterlock/rwlock.py#L125
 - The Writer algorithm internally use five locks https://github.com/elarivie/pyReaderWriterLock/blob/5569662f3cab997a22b50522794afe0258c09850/readerwriterlock/rwlock.py#L204
 - Also some of the downgradable version of the above locks strategy use a lock for a thread safe int counter https://github.com/elarivie/pyReaderWriterLock/blob/5569662f3cab997a22b50522794afe0258c09850/readerwriterlock/rwlock.py#L62

ReaderWriterLocks are not a silver bullet.

**Cons:** ReaderWriterLock are slower than simple lock, it's a fact.
**Pros:** But at the cost of speed, it brings the feature of allowing more than one reader to process simultaneously which reduce the perceptible processing time.

Now base on your use case, if (Cons < Pros) then ReaderWriterLock are a good fit, else use a Lock.


**Some idea of speed optimisation:**

- You should first look at your data crunching algorithm for speed optimisation.
- You could use strategy to reduce processing like caching (would reduce process time and the amount of read acquiring lock)
- Batch writing with the use of a Debouncer/Throttler(this would reduce the amount of write acquiring lock)

Speed seems to be your main goal... if speed is really an issue, at one point you may have to reconsider your design decision of using Python and use a compiled language instead.

Don't forget that Python is plagued by the [GIL](https://en.wikipedia.org/wiki/Global_interpreter_lock) and true parallel processing is not possible.
