### ISSUE TITLE
Document upgrading the lock

### ISSUE THREAD

**Issue by cool-RR** [elarivie/pyReaderWriterLock#12]
I can't figure out how I'm supposed to upgrade a lock from read to write. I can't find the word "upgrade" anywhere in this repo. I think there should be an example in the readme, or at least in the tests.

**Comment by elarivie** [comment]
Hello @cool-RR,

It is possible to atomically downgrade locks from writer -> reader lock but there is effectively no way to atomically upgrade a reader lock to writer lock.

If you want to upgrade a lock (not atomically) you can unlock the acquired read lock and then acquire a new writer lock.

Conceptually atomically upgrading reader lock -> writer lock does not make much sens mainly when considering the use case where more than one reader lock want to upgrade at the same time.

**Comment by cool-RR** [comment]
Ah, I understand my mistake now. That makes sense.
