### ISSUE TITLE
Request for creating a release

### ISSUE THREAD

**Issue by MayNiklas** [elarivie/pyReaderWriterLock#15]
Hello!

I want to package the pyReaderWriterLock library for Nixpkgs, which is a popular package manager for the Nix OS and other Nix-based systems. Creating a package for Nixpkgs would make it easier for users to use the library in declarative and reproducable environments.

To achieve this, I kindly request you to create a release for the pyReaderWriterLock project. Having a release would make it more convenient to package the library for Nixpkgs. We try to avoid referencing the master branch when possible.

Thank you for your time and consideration.

Best regards,
MayNiklas

**Comment by elarivie** [comment]
Hello @MayNiklas,

I honestly have no idea what **Nixpkgs** is, a google search pointed me at https://github.com/NixOS/nixpkgs

the project readerwriterlock is already available from pypi at https://pypi.org/project/readerwriterlock/

And you probably already know that it is available with the command
```shell
python3 -m pip install -U readerwriterlock
```

To create a nixpkgs I will need much more information than 

> _create a release_

I am not saying no; it's just that I have no idea how to do it, where to start, how to test it, and, most importantly, I will then have to maintain it in the future.

Is it something that you can partially contribute by creating a pull request?


So I am fully open to create a nixpkgs release **with your help**.

if you inspect the code of the project you'll notice the presence of a [makefile at the root which contains logic to package and publish new release to pypi](https://github.com/elarivie/pyReaderWriterLock/blob/e7382855cdd46c9d54b2d697c48c00b8fd7e4c81/GNUmakefile#L148)

you could create a pull request which would add targets to create a release and publish it for nixpkgs, etc…


**Note:** this kind of task will most probably need a lot of ping-pong discussion, so feel free to contact me by email

Éric Larivière\<ericlariviere@hotmail.com>

**Comment by elarivie** [comment]
I created the release [v1.0.9](https://github.com/elarivie/pyReaderWriterLock/releases/tag/v1.0.9)

And I will create new github tag/release for every future version change.

Question @MayNiklas, when let say v1.0.10 will exist, will I have something to do other than creating a new tag/release in github to make nixpkgz happy? … will I have to bumb the version on nixpkgz somewhere? or it detects new releases automatically?

**Comment by MayNiklas** [comment]
@elarivie Thank you for creating the release!

Since you are creating a new tag / release, our tooling will be able to detect that automatically:
PR's are getting created by bots -> those trigger the CI/CD -> tests are getting executed -> PR's are getting reviewed by humans.

You won't have to think about the Nixpkgs stuff at all :)
