### ISSUE TITLE
Source tarball is broken because it doesn't contain README.rst

### ISSUE THREAD

**Issue by mpickering** [elarivie/pyReaderWriterLock#3]
Downloading this source tarball leads to an uninstallable package because it doesn't contain README.rst. 

https://files.pythonhosted.org/packages/17/8e/66256c540b21bdc18ce46abe1b2294ea6b167a9cde8cd58ef62a0cd0cf3f/readerwriterlock-1.0.4.tar.gz

**Comment by elarivie** [comment]
Hello @mpickering,

Sorry for the issue that you encountered

Could you please provide more information:
1- The install command line that you use
2- The uninstall command line that you use.
3- The error that you get

4- On which environment are you 
- Linux/windows?
- Which version of python?

Thanks

**Comment by elarivie** [comment]
Hello @mpickering 

This issue is fixed in v1.0.5

The following files are now included in the source tarball:
README.md 
README.rst
