### ISSUE TITLE
Useable with RLock?

### ISSUE THREAD

**Issue by Serpens66** [elarivie/pyReaderWriterLock#9]
Hi,

Thank you very much for your work! :)

how can I use this with threading.RLock()? 
I used lock_factory in this test code: 

```
a = rwlock.RWLockFair(lock_factory=lambda: threading.RLock())
lock = a.gen_rlock()
lock.acquire()
lock.acquire()
lock.release()
lock.release()
```

But second release line triggers the line:
"if not self.v_locked: raise RELEASE_ERR_CLS(RELEASE_ERR_MSG)"
of course. 
So it seems your code does not work for RLock() right?

Can you also make it work for RLock?

**Comment by Serpens66** [comment]
sorry, did not see you already answered this https://github.com/elarivie/pyReaderWriterLock/issues/5

**Comment by elarivie** [comment]
Hello @Serpens66 , thanks for your kind word about the work done to create readerwriterlock.

Note that in gen_rlock(), the 'r'  stands for "reader" lock, not "reentrant" lock

Effectively, as you have found by reading #5 , reentrant lock are not supported, and won't be.
